import type { Place } from "./types";
import { PLACE_PHOTOS } from "./place-photos";

/**
 * 서울역·용산역·신용산역·삼각지 인근 실제 식당 20곳. 캐치테이블·다이닝코드·테이블링·블로그
 * 웹 검색으로 조사한 뒤 사용자가 검수한 데이터입니다(2026-07-20 기준). 좌표는 카카오 로컬 API로
 * 확보한 정확한 값이며, 지도 링크도 실제 업체 상세 페이지입니다.
 */

function buildMapUrls(name: string, address: string, kakaoUrl: string, naverUrl?: string) {
  const q = encodeURIComponent(`${name} ${address}`);
  return {
    // naverUrl을 안 넘기면 검색 결과 링크로 대체한다 — 검색 결과는 동명이인 매장이 여러 개
    // 뜨거나 엉뚱한 곳이 먼저 나올 수 있어 정확하지 않다. kakaoUrl처럼 각 장소의 실제
    // 상세 페이지 URL(예: https://map.naver.com/p/entry/place/12345678)을 넣어주면
    // 그쪽이 우선한다.
    mapUrlNaver: naverUrl ?? `https://map.naver.com/p/search/${q}`,
    mapUrlKakao: kakaoUrl,
  };
}

function place(
  p: Omit<Place, "mapUrlNaver" | "mapUrlKakao" | "photos"> & { kakaoUrl: string; naverUrl?: string },
): Place {
  const { kakaoUrl, naverUrl, ...rest } = p;
  return {
    ...rest,
    ...buildMapUrls(p.name, p.address, kakaoUrl, naverUrl),
    photos: PLACE_PHOTOS[p.name] ?? [],
  };
}

export const PLACES: Place[] = [
  place({
    id: "housum-ipark",
    name: "호우섬 용산아이파크몰점",
    category: "홍콩식 딤섬 전문점",
    cuisineTags: ["chinese"],
    area: "yongsan",
    address: "서울 용산구 한강대로23길 55",
    businessHours: "매일 11:00-22:00(라스트오더 21:00)",
    lat: 37.5288004653396,
    lng: 126.964553141576,
    kakaoUrl: "http://place.map.kakao.com/832404417",
    naverUrl: "https://naver.me/G9r5bY3z",
    priceMin: 15000,
    priceMax: 30000,
    capacityMin: 1,
    capacityMax: 8,
    relationshipTags: ["close-friend", "friend-group", "coworker"],
    formalityTags: ["casual", "balanced"],
    conversationScore: 5,
    hospitalityScore: 5,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "moderate",
    seatType: "open",
    spaceScore: 5,
    privateRoomAvailable: false,
    reservationMethod: "unavailable",
    waitingRisk: 5,
    parkingAvailable: true,
    parkingType: "partner",
    curatedReason: "아이파크몰 내에 있어 접근성이 좋고 캐주얼하게 즐기는 홍콩식 딤섬 전문점으로 부담 없는 모임에 어울려요",
    cautionNote: "예약을 받지 않고 현장 웨이팅(대기 등록) 방식으로만 운영되며 주차요금이 10분당 1500원으로 비싼 편이라 사전 정산 확인이 필요하고 룸 여부는 확인되지 않았어요",
    menu: [
      { name: "블랙 하가우(3pcs)", price: 9500 },
      { name: "맑은 우육탕면", price: 15400 },
      { name: "마라완탕비빔면", price: 15400 },
      { name: "크리스피라페치킨", price: 27900 },
      { name: "마늘칩꿔바육", price: 29900 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "maze-sukiyaki",
    name: "마제스키야키",
    category: "관동식 스키야키·샤브샤브 전문점",
    cuisineTags: ["japanese", "meat"],
    area: "sinyongsan",
    address: "서울 용산구 한강대로40길 9-5",
    businessHours: "매일 11:30-23:00(브레이크타임 15:00-17:00 라스트오더 22:00)",
    lat: 37.5305616101013,
    lng: 126.969919467791,
    kakaoUrl: "http://place.map.kakao.com/2096597117",
    naverUrl: "https://naver.me/55rm7zfn",
    priceMin: 21000,
    priceMax: 45000,
    capacityMin: 2,
    capacityMax: 10,
    relationshipTags: ["close-friend", "friend-group", "family"],
    formalityTags: ["hospitable", "balanced"],
    conversationScore: 8,
    hospitalityScore: 8,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "moderate",
    seatType: "semi-private",
    spaceScore: 5,
    privateRoomAvailable: false,
    reservationMethod: "phone",
    waitingRisk: 8,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "고급스럽고 아늑한 분위기의 관동식 스키야키 전문점으로 수다 떨며 대화하기 좋아 친구·가족 모임에 적합해요",
    cautionNote: "자체 주차장이 없어 인근 공영주차장을 이용해야 하며 점심·저녁 피크타임 웨이팅이 잦아 네이버예약/캐치테이블로 사전 예약(네이버 예약 시 1인 1만원 예약금)하는 것이 확실하고 주말 당일 워크인은 어려운 편이에요",
    menu: [
      { name: "우목심(런치)", price: 19000 },
      { name: "등심(런치)", price: 21000 },
      { name: "살치살(런치)", price: 23000 },
      { name: "와규(런치)", price: 37000 },
      { name: "트러플 크로켓", price: 12000 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "omokjip-samgakji",
    name: "오목집 삼각지점",
    category: "족발 전문 한식당",
    cuisineTags: ["korean"],
    area: "samgakji",
    address: "서울 용산구 한강대로62길 7",
    businessHours: "매일 16:00-23:00",
    lat: 37.5345566954557,
    lng: 126.973902716688,
    kakaoUrl: "http://place.map.kakao.com/1539152502",
    naverUrl: "https://naver.me/xmxIFjLb",
    priceMin: 20000,
    priceMax: 35000,
    capacityMin: 2,
    capacityMax: 10,
    relationshipTags: ["close-friend", "coworker", "family"],
    formalityTags: ["casual", "balanced"],
    conversationScore: 5,
    hospitalityScore: 5,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "moderate",
    seatType: "wide",
    spaceScore: 8,
    privateRoomAvailable: false,
    reservationMethod: "phone",
    waitingRisk: 5,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "넓고 정갈한 좌석 배치로 편안한 분위기에서 족발과 함께 모임을 즐기기 좋은 곳이에요",
    cautionNote: "온라인 예약 채널(캐치테이블·네이버예약)은 이 지점에서 확인되지 않아 전화(02-797-6882)로 예약해야 하며 자체 주차장 정보가 확인되지 않아 인근 공영주차장 이용이 필요할 수 있어요",
    // 이 지점 전용 자료를 찾지 못해 가격이 확인된 2개만 실었다(다른 5곳처럼 5개를 채우지 않음)
    menu: [
      { name: "족발(대)", price: 44000 },
      { name: "모듬족발", price: 48000 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "cucciolo-seoul",
    name: "쿠촐로서울",
    category: "이탈리안 레스토랑",
    cuisineTags: ["western"],
    area: "sinyongsan",
    address: "서울 용산구 한강대로 100",
    businessHours: "매일 11:30-22:00(브레이크타임 14:30-17:30)",
    lat: 37.5287908181114,
    lng: 126.96867345247902,
    kakaoUrl: "http://place.map.kakao.com/1729633606",
    naverUrl: "https://naver.me/5T4AiI8r",
    priceMin: 40000,
    priceMax: 70000,
    capacityMin: 1,
    capacityMax: 12,
    relationshipTags: ["workplace-senior", "family", "close-friend"],
    formalityTags: ["formal", "hospitable"],
    conversationScore: 8,
    hospitalityScore: 8,
    serviceScore: 8,
    accessScore: 8,
    noiseLevel: "quiet",
    seatType: "room",
    spaceScore: 8,
    privateRoomAvailable: true,
    roomMinCapacity: 4,
    roomTimeLimitMinutes: 120,
    reservationMethod: "phone",
    waitingRisk: 5,
    parkingAvailable: true,
    parkingType: "partner",
    curatedReason: "아모레퍼시픽 건물 내 위치한 고급스럽고 조용한 이탈리안 레스토랑으로 프라이빗 룸이 있어 격식 있는 접대나 모임에 적합해요",
    cautionNote: "룸은 4인 이상부터 예약 가능하며 이용 시 차지비용 5만원이 별도로 부과돼요. 캐치테이블 예약이 활발하고 예약 없이도 약간의 대기 후 이용 가능한 편이나 건물 주차장은 2시간 무료 제공에 평일엔 여유가 없는 경우가 있어요",
    menu: [
      { name: "양 안심 스테이크", price: 43000 },
      { name: "봉골레소스 농어구이", price: 49000 },
      { name: "로스트 치킨", price: 41000 },
      { name: "피쉬앤칩스(런치)", price: 31000 },
      { name: "티라미수", price: 12000 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "yongsan-bongsunga",
    name: "용산봉숭아",
    category: "향토음식 기반 한식 실내포차",
    cuisineTags: ["korean", "seafood", "wine-alcohol"],
    area: "yongsan",
    address: "서울 용산구 한강대로15길 18",
    businessHours: "월~금 16:30-24:00, 토·일·공휴일 16:00-24:00(라스트오더 23:00)",
    lat: 37.5261692355007,
    lng: 126.963553194003,
    kakaoUrl: "http://place.map.kakao.com/1107895548",
    naverUrl: "https://naver.me/FO9ovRwV",
    priceMin: 25000,
    priceMax: 45000,
    capacityMin: 2,
    capacityMax: 12,
    relationshipTags: ["close-friend", "friend-group", "coworker"],
    formalityTags: ["casual", "balanced"],
    conversationScore: 8,
    hospitalityScore: 5,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "moderate",
    seatType: "room",
    spaceScore: 5,
    privateRoomAvailable: true,
    roomMinCapacity: 4,
    roomTimeLimitMinutes: 120,
    reservationMethod: "phone",
    waitingRisk: 8,
    parkingAvailable: true,
    parkingType: "self",
    curatedReason: "4~5인부터 최대 12명까지 이용 가능한 룸이 있어 조용하게 대화하며 청첩장 모임이나 생일 파티를 하기 좋은 실내포차예요",
    cautionNote: "주차공간이 협소하고 주말에는 웨이팅이 많아 캐치테이블·네이버예약으로 사전 예약이 필수이며 다만 테라스(야장)석은 예약을 받지 않고 현장 방문 순으로 운영돼요",
    menu: [
      { name: "광주식 오리감자탕", price: 34000 },
      { name: "제철 숙성 모듬회", price: 45000 },
      { name: "1++한우 영천식 미나리육회", price: 29000 },
      { name: "청도미나리 새우전", price: 20000 },
      { name: "순천식 돼지곱창전골", price: 28000 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "agra-ipark",
    name: "아그라 용산아이파크몰점",
    category: "인도음식(커리) 전문점",
    cuisineTags: ["western"],
    area: "yongsan",
    address: "서울 용산구 한강대로23길 55",
    businessHours: "매일 11:00-22:00(라스트오더 21:00)",
    lat: 37.5297717997967,
    lng: 126.964735959893,
    kakaoUrl: "http://place.map.kakao.com/321274321",
    naverUrl: "https://naver.me/5oE5CPG7",
    priceMin: 30000,
    priceMax: 40000,
    capacityMin: 1,
    capacityMax: 130,
    relationshipTags: ["close-friend", "family"],
    formalityTags: ["hospitable"],
    conversationScore: 8,
    hospitalityScore: 8,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "moderate",
    seatType: "wide",
    spaceScore: 8,
    privateRoomAvailable: false,
    reservationMethod: "phone",
    waitingRisk: 2,
    parkingAvailable: true,
    parkingType: "partner",
    curatedReason: "고급스러운 인테리어와 넓은 좌석으로 대화하며 식사하기 좋고 난·밥 무한리필로 가성비도 좋아요",
    cautionNote: "인도 커리 전문점이며 개별 룸은 없는 오픈형 매장이라 완전한 프라이버시가 필요한 자리에는 부적합해요",
    menu: [
      { name: "인디아 세트(평일)", price: 18600 },
      { name: "프리미엄 싱글(1인)", price: 29800 },
      { name: "프리미엄 커플(2인)", price: 59600 },
      { name: "프리미엄 트리플(3인)", price: 89400 },
      { name: "프리미엄 패밀리(4인)", price: 118700 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "hallyangjuga",
    name: "한량주가",
    category: "한식 주점(요리주점)",
    cuisineTags: ["korean", "wine-alcohol"],
    area: "samgakji",
    address: "서울 용산구 이태원로 5",
    businessHours: "월~금 17:00-01:00, 토~일 15:00-01:00",
    lat: 37.535436300677,
    lng: 126.974958035371,
    kakaoUrl: "http://place.map.kakao.com/929159824",
    naverUrl: "https://naver.me/xSFa5FdF",
    priceMin: 30000,
    priceMax: 50000,
    capacityMin: 2,
    capacityMax: 40,
    relationshipTags: ["close-friend", "friend-group", "coworker"],
    formalityTags: ["casual", "balanced"],
    conversationScore: 5,
    hospitalityScore: 5,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "lively",
    seatType: "semi-private",
    spaceScore: 5,
    privateRoomAvailable: false,
    reservationMethod: "phone",
    waitingRisk: 5,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "1981년부터 이어온 삼각지 생탕 맛집으로 단체석·연인석·1인석 등 좌석 구성이 다양해 여러 관계의 모임에 두루 어울려요",
    cautionNote: "온라인 예약 채널이 확인되지 않아 전화로만 예약 가능하며 금요일 저녁은 대기가 생길 수 있어 사전 예약을 권장해요. 매장 주차는 불가하며 전쟁기념관 북문 쪽 소형차 주차장을 이용해야 해요",
    menu: [
      { name: "갑오징어회", price: 45000 },
      { name: "들기름막국수&냉제육", price: 29000 },
      { name: "수비드목살&수제스팸구이", price: 29000 },
      { name: "얼큰스지전골", price: 35000 },
      { name: "두부김치", price: 25000 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "ililhyang-yongsan",
    name: "일일향 용산점",
    category: "중식 코스요리 전문점",
    cuisineTags: ["chinese"],
    area: "sinyongsan",
    address: "서울 용산구 한강대로40길 26 2층",
    businessHours: "매일 11:30-21:30(브레이크타임 14:30-17:00 라스트오더 20:45)",
    lat: 37.53004281298322,
    lng: 126.97063355773133,
    kakaoUrl: "http://place.map.kakao.com/185719220",
    naverUrl: "https://naver.me/GipB7xLv",
    priceMin: 30000,
    priceMax: 80000,
    capacityMin: 2,
    capacityMax: 10,
    relationshipTags: ["coworker", "workplace-senior", "family", "friend-group"],
    formalityTags: ["hospitable"],
    conversationScore: 8,
    hospitalityScore: 8,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "moderate",
    seatType: "room",
    spaceScore: 8,
    privateRoomAvailable: true,
    roomMinCapacity: 4,
    reservationMethod: "phone",
    waitingRisk: 5,
    parkingAvailable: true,
    parkingType: "valet",
    curatedReason: "프라이빗 룸을 다수 보유해 회식·접대 모임에 적합하며 두꺼운 탕수육 등 코스요리로 유명해요",
    cautionNote: "룸 예약은 최소 1주 전 예약을 권장하며 발렛비는 3000원 별도예요",
    menu: [
      { name: "원조 어향동고", price: 48000 },
      { name: "원조 육즙탕수육", price: 36000 },
      { name: "멘보샤(8pcs)", price: 49000 },
      { name: "옛날짬뽕(밥)", price: 12000 },
      { name: "짜장면(밥)", price: 9000 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "mimiok-sinyongsan",
    name: "미미옥 신용산점",
    category: "한국식 쌀국수·샤브샤브 전문점",
    cuisineTags: ["korean", "seafood"],
    area: "sinyongsan",
    address: "서울 용산구 한강대로15길 27",
    businessHours: "매일 11:00-22:00(평일 브레이크타임 15:00-17:00 라스트오더 21:30)",
    lat: 37.5262843768463,
    lng: 126.962952421499,
    kakaoUrl: "http://place.map.kakao.com/256180379",
    naverUrl: "https://naver.me/5CW7wNQJ",
    priceMin: 25000,
    priceMax: 40000,
    capacityMin: 2,
    capacityMax: 8,
    relationshipTags: ["close-friend", "friend-group", "coworker"],
    formalityTags: ["balanced"],
    conversationScore: 5,
    hospitalityScore: 5,
    serviceScore: 8,
    accessScore: 8,
    noiseLevel: "lively",
    seatType: "open",
    spaceScore: 5,
    privateRoomAvailable: false,
    reservationMethod: "phone",
    waitingRisk: 8,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "블루리본 선정 샤브샤브·쌀국수 맛집으로 플레이팅이 깔끔하고 서비스가 친절해 대접하는 자리에도 좋아요",
    cautionNote: "인기가 많아 예약 없이 방문 시 웨이팅이 자주 발생하며 캐치테이블 예약 시 인당 1만원의 예약금이 필요해요. 매장 주차는 불가해요",
    menu: [
      { name: "[2인분] 살치살 샤브", price: 43500 },
      { name: "1++ 프리미엄 한우찜", price: 59000 },
      { name: "1++ 한우 아롱사태 참나물 수육", price: 27000 },
      { name: "1++ 한우 육회", price: 23000 },
      { name: "빠삭! 한돈 미나리전", price: 17500 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "gaumont-yongsan",
    name: "고메드용산",
    category: "이자카야(일본식 주점)",
    cuisineTags: ["japanese", "wine-alcohol"],
    area: "samgakji",
    address: "서울 용산구 한강대로54길 25 지하1층·1층",
    businessHours: "월~금 16:30-03:00(라스트오더 02:00), 토~일 15:30-03:00(라스트오더 02:00)",
    lat: 37.5326013187338,
    lng: 126.97299263049,
    kakaoUrl: "http://place.map.kakao.com/415809500",
    naverUrl: "https://naver.me/xiqDHGNm",
    priceMin: 30000,
    priceMax: 50000,
    capacityMin: 2,
    capacityMax: 20,
    relationshipTags: ["close-friend", "friend-group", "coworker"],
    formalityTags: ["hospitable"],
    conversationScore: 5,
    hospitalityScore: 8,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "lively",
    seatType: "semi-private",
    spaceScore: 8,
    privateRoomAvailable: false,
    reservationMethod: "phone",
    waitingRisk: 5,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "동굴과 폭포 컨셉의 독특한 인테리어를 갖춘 신흥 이자카야로 사시미·모츠나베 등 메뉴가 다양하고 분위기가 뛰어나요",
    cautionNote: "매장 주차는 불가해 인근 공영주차장을 이용해야 하며 라스트오더가 새벽 2시로 늦어 귀가 수단을 미리 고려해야 해요. 온라인 예약 채널은 확인되지 않아 전화 예약을 권장해요",
    menu: [
      { name: "모듬사시미", price: 54000 },
      { name: "고메드 오합", price: 57000 },
      { name: "한우 육사시미", price: 37000 },
      { name: "우나기 봉초밥", price: 27000 },
      { name: "고등어 봉초밥", price: 26000 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "simpatikus-yongsan",
    name: "심퍼티쿠시 용산점",
    category: "유러피언 캐주얼 다이닝(파스타·스테이크·와인)",
    cuisineTags: ["western", "wine-alcohol"],
    area: "samgakji",
    address: "서울 용산구 한강대로52길 17-3",
    businessHours:
      "월-금 11:00-22:00(브레이크타임 15:00-17:00, 라스트오더 21:00), 토-일 11:30-22:00(브레이크타임 15:30-17:00, 라스트오더 21:00)",
    lat: 37.5321893478561,
    lng: 126.972075228216,
    kakaoUrl: "http://place.map.kakao.com/1740706159",
    naverUrl: "https://naver.me/GlJIuWur",
    priceMin: 30000,
    priceMax: 50000,
    capacityMin: 1,
    capacityMax: 8,
    relationshipTags: ["close-friend", "friend-group", "coworker"],
    formalityTags: ["balanced"],
    conversationScore: 5,
    hospitalityScore: 5,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "moderate",
    seatType: "open",
    spaceScore: 5,
    privateRoomAvailable: false,
    reservationMethod: "phone",
    waitingRisk: 8,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "고사리파스타·리조또 등 아시안 터치를 가미한 유러피언 메뉴와 와인을 삼각지역 도보권에서 캐주얼하게 즐길 수 있어 소규모 모임에 좋아요",
    cautionNote: "주말 저녁은 웨이팅이 잦은 편이고 전용 주차장이 없어 인근 공영주차장을 이용해야 해요",
    menu: [
      { name: "살치살 스테이크", price: 59000 },
      { name: "랍스터 비스큐 로제 파스타", price: 35000 },
      { name: "우대갈비 리조또", price: 39000 },
      { name: "라구 라자냐", price: 25500 },
      { name: "고추오일 명란크림 파스타", price: 22500 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "poi-kitchen",
    name: "포이키친",
    category: "퓨전일식 캐주얼 다이닝(용문시장 식재료 기반)",
    cuisineTags: ["japanese", "wine-alcohol"],
    area: "yongsan",
    address: "서울 용산구 새창로 128-9",
    businessHours: "매주 월요일 휴무, 화-일 17:00-23:00",
    lat: 37.535983826471,
    lng: 126.960692665106,
    kakaoUrl: "http://place.map.kakao.com/1582696611",
    naverUrl: "https://naver.me/GctrRylt",
    priceMin: 10000,
    priceMax: 40000,
    capacityMin: 1,
    capacityMax: 6,
    relationshipTags: ["close-friend", "coworker"],
    formalityTags: ["casual"],
    conversationScore: 5,
    hospitalityScore: 5,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "moderate",
    seatType: "open",
    spaceScore: 5,
    privateRoomAvailable: false,
    reservationMethod: "phone",
    waitingRisk: 5,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "용문시장에서 장을 본 제철 식재료로 만든 퓨전 요리와 사케·위스키·소주를 함께 즐길 수 있는 캐주얼 다이닝이에요",
    cautionNote: "좌석 규모·정확한 예약 채널에 대한 자료가 부족해 방문 전 전화 확인을 권장해요. 월요일은 휴무예요",
    // 메뉴명(전복파스타·우니파스타 등)은 여러 후기에서 확인되지만 가격을 확인할 수 있는
    // 자료를 찾지 못해 비워둔다. 없는 값을 지어내는 대신 빈 배열로 둔다
    menu: [],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "shawnino",
    name: "쇼니노",
    category: "이탈리안 브런치 바(박제현 셰프)",
    cuisineTags: ["western", "brunch-cafe"],
    area: "yongsan",
    address: "서울 용산구 한강대로21길 17-18",
    businessHours:
      "월요일 휴무, 화-금 10:00-22:00(브레이크타임 16:00-18:00), 토 10:00-22:00(브레이크타임 17:30-18:00), 일 09:00-20:00",
    lat: 37.526381803677765,
    lng: 126.96333248819927,
    kakaoUrl: "http://place.map.kakao.com/232272017",
    naverUrl: "https://naver.me/FqWtmqpD",
    priceMin: 25000,
    priceMax: 45000,
    capacityMin: 1,
    capacityMax: 6,
    relationshipTags: ["close-friend", "family"],
    formalityTags: ["balanced"],
    conversationScore: 2,
    hospitalityScore: 5,
    serviceScore: 8,
    accessScore: 8,
    noiseLevel: "lively",
    seatType: "open",
    spaceScore: 2,
    privateRoomAvailable: false,
    reservationMethod: "phone",
    waitingRisk: 8,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "흑백요리사 출연 셰프가 운영하는 포지타노풍 인테리어의 이탈리안 브런치 맛집으로 브루스케타·시푸드 오일 파스타 등 시그니처 메뉴 평이 좋고 캐치테이블로 예약이 가능해요",
    cautionNote: "테이블 간격이 좁아 옆자리와 가까운 편이고 월요일은 휴무이며 디너 타임에는 주류 주문이 필수예요",
    menu: [
      { name: "Tenderloin Steak", price: 43000 },
      { name: "Seafood Oil Pasta", price: 27900 },
      { name: "Truffle Carbonara", price: 26900 },
      { name: "Squid Ink Risotto", price: 26500 },
      { name: "Homemade Tiramisu", price: 11900 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "munch-yongsan",
    name: "먼치 용산",
    category: "캐주얼 다이닝 바(파스타·와인)",
    cuisineTags: ["western", "wine-alcohol"],
    area: "sinyongsan",
    address: "서울 용산구 한강대로38가길 7-26",
    businessHours: "매일 11:30-22:00(브레이크타임 15:00-17:30)",
    lat: 37.5299264006725,
    lng: 126.969906146708,
    kakaoUrl: "http://place.map.kakao.com/1489848230",
    naverUrl: "https://naver.me/502MHzUS",
    priceMin: 35000,
    priceMax: 55000,
    capacityMin: 1,
    capacityMax: 6,
    relationshipTags: ["close-friend", "coworker"],
    formalityTags: ["balanced"],
    conversationScore: 8,
    hospitalityScore: 5,
    serviceScore: 8,
    accessScore: 8,
    noiseLevel: "quiet",
    seatType: "open",
    spaceScore: 5,
    privateRoomAvailable: false,
    reservationMethod: "phone",
    waitingRisk: 2,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "용리단길에 위치한 조용한 캐주얼 다이닝 바로 페코리노 치즈 리가토니·봉골레 파스타 등 시그니처 메뉴와 하우스와인이 좋은 평가를 받아요",
    cautionNote: "전용 주차장이 없어 주차가 어려운 편이며 내부 공간이 작아(7~8팀 규모) 예약 없이는 대기할 수 있어요",
    menu: [
      { name: "페코리노 치즈 리가토니", price: 19000 },
      { name: "덕 라구 카사레치아 파스타", price: 22000 },
      { name: "스파이시 쉬림프 파스타", price: 22000 },
      { name: "한우 비프 타르타르", price: 21000 },
      { name: "비프 프라임 스테이크", price: 39000 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "crystal-jade-ipark",
    name: "크리스탈제이드 용산아이파크몰점",
    category: "정통 상해식 중식당(딤섬 전문)",
    cuisineTags: ["chinese"],
    area: "yongsan",
    address: "서울 용산구 한강대로23길 55",
    businessHours: "매일 11:00-22:00(브레이크타임 15:00-16:00 라스트오더 21:30)",
    lat: 37.5288779548606,
    lng: 126.9645644182274,
    kakaoUrl: "http://place.map.kakao.com/1667431464",
    naverUrl: "https://naver.me/xWTneybc",
    priceMin: 20000,
    priceMax: 45000,
    capacityMin: 1,
    capacityMax: 16,
    relationshipTags: ["family", "workplace-senior", "coworker"],
    formalityTags: ["hospitable"],
    conversationScore: 5,
    hospitalityScore: 8,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "moderate",
    seatType: "room",
    spaceScore: 8,
    privateRoomAvailable: true,
    reservationMethod: "phone",
    waitingRisk: 8,
    parkingAvailable: true,
    parkingType: "partner",
    curatedReason: "소롱포 등 정통 상해식 딤섬과 프라이빗 룸을 갖춰 격식 있는 소규모 접대·모임에 적합하며 아이파크몰 주차 연계로 접근성도 좋아요",
    cautionNote: "대기가 많은 편이라 예약 없이는 웨이팅이 길 수 있으며 룸 최소 인원·주문 금액 등 세부 조건은 자료로 확인되지 않아 방문 전 문의가 필요해요",
    menu: [
      { name: "싱가포르식 흑후추 마늘 소고기 안심", price: 50000 },
      { name: "깐풍기", price: 39000 },
      { name: "광동식 탕수육", price: 37000 },
      { name: "딴딴면", price: 15000 },
      { name: "오리지널 소롱포(6pcs)", price: 9500 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "burnwood-yongsan",
    name: "버누드",
    category: "다이닝바",
    cuisineTags: ["korean", "meat", "wine-alcohol"],
    area: "sinyongsan",
    address: "서울 용산구 한강대로21길 17-7 2층",
    businessHours: "매일 17:00-24:00",
    lat: 37.5264919077692,
    lng: 126.963922970795,
    kakaoUrl: "http://place.map.kakao.com/1815712320",
    naverUrl: "https://naver.me/FZ27hhJH",
    priceMin: 18000,
    priceMax: 35000,
    capacityMin: 2,
    capacityMax: 6,
    relationshipTags: ["close-friend", "other"],
    formalityTags: ["balanced"],
    conversationScore: 5,
    hospitalityScore: 5,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "moderate",
    seatType: "open",
    spaceScore: 5,
    privateRoomAvailable: false,
    reservationMethod: "phone",
    waitingRisk: 5,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "신용산역 도보 6분 거리의 신상 다이닝바로, 숯불요리 기반 안주 메뉴가 있어 소개팅이나 소규모 모임 장소로 추천돼요",
    cautionNote: "매장 자체 주차 공간은 없어 인근 민영 주차장을 이용해야 해요",
    // 가격대(18,000~35,000원)만 확인되고 개별 메뉴명+가격 페어는 찾지 못해 비워둔다
    menu: [],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "yangbokjeom-yongsan",
    name: "양복점 용산점",
    category: "양꼬치 전문점",
    cuisineTags: ["meat"],
    area: "sinyongsan",
    address: "서울 용산구 새창로 209 1층",
    businessHours: "월~금 15:30-24:00(라스트오더 23:00), 토·일 14:30-24:00(라스트오더 23:00)",
    lat: 37.5306743586309,
    lng: 126.9670073041,
    kakaoUrl: "http://place.map.kakao.com/1925523497",
    naverUrl: "https://naver.me/GkR3b3zr",
    priceMin: 30000,
    priceMax: 50000,
    capacityMin: 2,
    capacityMax: 10,
    relationshipTags: ["close-friend", "friend-group", "coworker"],
    formalityTags: ["casual"],
    conversationScore: 5,
    hospitalityScore: 2,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "lively",
    seatType: "semi-private",
    spaceScore: 5,
    privateRoomAvailable: true,
    roomMinCapacity: 6,
    reservationMethod: "phone",
    waitingRisk: 8,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "신용산역 도보 5분 거리, 다양한 소스와 질 좋은 양꼬치, 2층 룸에서 단체 모임이 가능해요",
    cautionNote: "평일 저녁에도 웨이팅이 있을 수 있어 캐치테이블·테이블링으로 사전 확인을 추천해요. 전용 주차장 없어 인근 공영주차장을 이용해야 해요",
    menu: [
      { name: "양복점 꽃갈비(양갈비)", price: 28900 },
      { name: "양 등심꼬치", price: 25900 },
      { name: "양복점 왕꼬치(양꼬치)", price: 18900 },
      { name: "블랙 꿔바로우", price: 23000 },
      { name: "마라샹궈", price: 25000 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "una-yongsan",
    name: "우나 용산본점",
    category: "일식당",
    cuisineTags: ["japanese"],
    area: "sinyongsan",
    address: "서울 용산구 한강대로 37 에피소드 용산 2층",
    businessHours: "매일 11:30-22:00(브레이크타임 15:00-17:00)",
    lat: 37.5248338089062,
    lng: 126.9630979415,
    kakaoUrl: "http://place.map.kakao.com/1908727456",
    naverUrl: "https://naver.me/GHvq7leJ",
    priceMin: 42000,
    priceMax: 58000,
    capacityMin: 1,
    capacityMax: 8,
    relationshipTags: ["family", "coworker", "workplace-senior"],
    formalityTags: ["hospitable"],
    conversationScore: 8,
    hospitalityScore: 8,
    serviceScore: 8,
    accessScore: 8,
    noiseLevel: "quiet",
    seatType: "room",
    spaceScore: 8,
    privateRoomAvailable: true,
    roomMinCapacity: 4,
    reservationMethod: "phone",
    waitingRisk: 5,
    parkingAvailable: true,
    parkingType: "partner",
    curatedReason: "신용산역 인접, 히츠마부시를 현대적으로 재해석한 프라이빗 일식 다이닝으로 4~8인 룸을 보유해 소규모 모임에 적합해요",
    cautionNote: "브레이크타임(15:00-17:00)에는 이용이 어려우니 방문 시간을 미리 확인하는 게 좋아요",
    menu: [
      { name: "특 히츠마부시", price: 58000 },
      { name: "명란 히츠마부시", price: 52000 },
      { name: "히츠마부시(나고야식 장어덮밥)", price: 42000 },
      { name: "우나기 카바야키", price: 39000 },
      { name: "토리마부시(숯불닭구이덮밥)", price: 29000 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
  place({
    id: "taa-samgakji",
    name: "TAA",
    category: "와인바·라운지",
    cuisineTags: ["western", "wine-alcohol"],
    area: "samgakji",
    address: "서울 용산구 한강대로62길 45-11",
    businessHours: "월~목 18:00-24:00, 금 18:00-01:00, 토 15:00-01:00, 일 15:00-23:00(연중무휴)",
    lat: 37.53276818614936,
    lng: 126.97380151472287,
    kakaoUrl: "http://place.map.kakao.com/1951455212",
    naverUrl: "https://naver.me/F884LWhF",
    priceMin: 25000,
    priceMax: 45000,
    capacityMin: 2,
    capacityMax: 8,
    relationshipTags: ["close-friend", "friend-group", "other"],
    formalityTags: ["casual"],
    conversationScore: 5,
    hospitalityScore: 5,
    serviceScore: 5,
    accessScore: 8,
    noiseLevel: "lively",
    seatType: "semi-private",
    spaceScore: 8,
    privateRoomAvailable: false,
    reservationMethod: "phone",
    waitingRisk: 8,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "삼각지역 도보권의 힙한 와인바 라운지로, 테라스와 디제잉이 있는 개방적인 분위기에서 스테이크·파스타 등 다양한 메뉴를 즐길 수 있어요",
    cautionNote: "완전 독립된 룸은 아니고 오픈형·반분리형 단체석 위주라 프라이버시는 제한적이에요. 전용 주차장이 없어 인근 유료 공영주차장을 이용해야 해요. 주말은 웨이팅이 있어 예약을 추천해요",
    menu: [
      { name: "살치살 큐브 스테이크", price: 39000 },
      { name: "카프레제 치킨 슈니첼", price: 26000 },
      { name: "멜란자네 라구 파스타", price: 22000 },
      { name: "포르치니 리조또", price: 21000 },
      { name: "문어 아보카도 세비체", price: 20000 },
    ],
    lastVerifiedAt: "2026-07-20",
  }),
];

export function getPlaceById(id: string): Place | undefined {
  return PLACES.find((p) => p.id === id);
}

/**
 * 홈 화면 랭킹 섹션용 임시 정렬 기준. 실제 조회수·저장수 집계가 아직 없어서,
 * 이미 갖고 있는 큐레이션 점수(대접감·대화가능성·서비스·접근성 평균)로 대체한다.
 * 트래픽 데이터가 쌓이면 이 함수만 실집계 기준으로 바꾸면 된다.
 */
export function getTopRatedPlaces(limit = 5): Place[] {
  // 대접감·서비스 점수는 가격이 높은 장소일수록 자연히 높게 나오는 경향이 있다.
  // 순수 품질 점수만으로 정렬하면 홈 화면 첫인상이 고가 오마카세 위주로 쏠려,
  // "청첩장 모임"이라는 다양한 예산대의 실제 사용 맥락과 멀어진다.
  // 1인 평균가에 완만한 페널티를 줘서 가격대가 고르게 섞여 보이도록 보정한다.
  const valueScore = (p: Place) => {
    const quality = (p.hospitalityScore + p.conversationScore + p.serviceScore + p.accessScore) / 4;
    const avgPrice = (p.priceMin + p.priceMax) / 2;
    return quality - avgPrice / 50000;
  };
  return [...PLACES].sort((a, b) => valueScore(b) - valueScore(a)).slice(0, limit);
}
