import type { Place } from "./types";

/**
 * MVP 데모/프로토타이핑용 예시 데이터입니다.
 * 실제 존재하는 매장을 검증한 정보가 아니라 PRD 10.1 스키마 구조를 보여주기 위한
 * 플레이스홀더이며, 런칭 전 자체 큐레이션 데이터로 교체되어야 합니다(PRD 9.1 참고).
 * 지도 링크는 특정 리스팅을 단정하지 않도록 이름+주소 기반 "검색" 링크로 생성합니다.
 */

function buildMapUrls(name: string, address: string) {
  const q = encodeURIComponent(`${name} ${address}`);
  return {
    mapUrlNaver: `https://map.naver.com/p/search/${q}`,
    mapUrlKakao: `https://map.kakao.com/?q=${q}`,
  };
}

function place(p: Omit<Place, "mapUrlNaver" | "mapUrlKakao">): Place {
  return { ...p, ...buildMapUrls(p.name, p.address) };
}

export const PLACES: Place[] = [
  place({
    id: "onki-hansang",
    name: "온기한상 강남",
    category: "한정식",
    cuisineTags: ["korean"],
    area: "gangnam",
    address: "서울 강남구 강남대로94길 12 3층",
    lat: 37.4985,
    lng: 127.0281,
    priceMin: 45000,
    priceMax: 60000,
    capacityMin: 2,
    capacityMax: 8,
    relationshipTags: ["family", "workplace-senior", "coworker"],
    formalityTags: ["hospitable", "formal"],
    conversationScore: 8,
    hospitalityScore: 9,
    serviceScore: 9,
    accessScore: 8,
    noiseLevel: "quiet",
    seatType: "room",
    spaceScore: 8,
    privateRoomAvailable: true,
    roomMinCapacity: 4,
    roomMinOrderAmount: 200000,
    roomTimeLimitMinutes: 120,
    reservationMethod: "phone",
    waitingRisk: 2,
    parkingAvailable: true,
    parkingType: "valet",
    curatedReason:
      "가족이나 선배님을 모시는 자리에 어울리는 정갈한 한정식 코스로, 룸 좌석에서 조용히 대화하기 좋아요.",
    cautionNote: "저녁 시간대는 최소 3일 전 예약을 권장해요.",
    lastVerifiedAt: "2026-06-18",
  }),
  place({
    id: "sueot-sikdang",
    name: "수어당 논현",
    category: "한식",
    cuisineTags: ["korean"],
    area: "nonhyeon",
    address: "서울 강남구 논현로 645 2층",
    lat: 37.5105,
    lng: 127.023,
    priceMin: 50000,
    priceMax: 70000,
    capacityMin: 2,
    capacityMax: 6,
    relationshipTags: ["workplace-senior", "coworker", "family"],
    formalityTags: ["hospitable", "formal"],
    conversationScore: 9,
    hospitalityScore: 9,
    serviceScore: 9,
    accessScore: 6,
    noiseLevel: "quiet",
    seatType: "room",
    spaceScore: 8,
    privateRoomAvailable: true,
    roomMinCapacity: 4,
    roomMinOrderAmount: 250000,
    roomTimeLimitMinutes: 120,
    reservationMethod: "difficult",
    waitingRisk: 2,
    parkingAvailable: true,
    parkingType: "self",
    curatedReason:
      "선배나 상사를 모시는 자리에 맞춰진 룸 중심 한식당으로 대접하는 느낌이 확실해요.",
    cautionNote: "주말 저녁은 예약이 빨리 마감되니 1주일 전에는 확인해보세요.",
    lastVerifiedAt: "2026-06-10",
  }),
  place({
    id: "nonhyeon-sushi-on",
    name: "스시온 논현",
    category: "일식·오마카세",
    cuisineTags: ["japanese"],
    area: "nonhyeon",
    address: "서울 강남구 논현로145길 8 1층",
    lat: 37.5118,
    lng: 127.0218,
    priceMin: 90000,
    priceMax: 130000,
    capacityMin: 2,
    capacityMax: 4,
    relationshipTags: ["close-friend", "workplace-senior", "coworker"],
    formalityTags: ["hospitable", "formal"],
    conversationScore: 7,
    hospitalityScore: 10,
    serviceScore: 9,
    accessScore: 7,
    noiseLevel: "quiet",
    seatType: "semi-private",
    spaceScore: 7,
    privateRoomAvailable: false,
    reservationMethod: "difficult",
    waitingRisk: 1,
    parkingAvailable: true,
    parkingType: "valet",
    curatedReason:
      "특별히 대접하고 싶은 소수 모임에 맞는 오마카세로, 격식 있는 분위기를 원할 때 좋아요.",
    cautionNote: "예약이 2주 전에 마감되는 경우가 많아 서둘러야 해요.",
    lastVerifiedAt: "2026-05-30",
  }),
  place({
    id: "le-pavillon",
    name: "르파비용 신논현",
    category: "프렌치 다이닝",
    cuisineTags: ["western"],
    area: "sinnonhyeon",
    address: "서울 서초구 서초대로77길 20 4층",
    lat: 37.5038,
    lng: 127.0242,
    priceMin: 80000,
    priceMax: 110000,
    capacityMin: 2,
    capacityMax: 6,
    relationshipTags: ["workplace-senior", "coworker"],
    formalityTags: ["formal", "hospitable"],
    conversationScore: 8,
    hospitalityScore: 10,
    serviceScore: 10,
    accessScore: 8,
    noiseLevel: "quiet",
    seatType: "room",
    spaceScore: 9,
    privateRoomAvailable: true,
    roomMinCapacity: 4,
    roomMinOrderAmount: 400000,
    roomTimeLimitMinutes: 150,
    reservationMethod: "difficult",
    waitingRisk: 2,
    parkingAvailable: true,
    parkingType: "valet",
    curatedReason: "격식 있게 대접해야 하는 상사·선배 모임에 맞는 코스 다이닝이에요.",
    cautionNote: "코스 진행 시간이 길어 2시간 이상 여유를 두는 게 좋아요.",
    lastVerifiedAt: "2026-06-01",
  }),
  place({
    id: "hwaroyeon",
    name: "화로연 강남점",
    category: "숯불구이",
    cuisineTags: ["meat"],
    area: "gangnam",
    address: "서울 강남구 강남대로 428 지하1층",
    lat: 37.4972,
    lng: 127.0268,
    priceMin: 35000,
    priceMax: 50000,
    capacityMin: 4,
    capacityMax: 10,
    relationshipTags: ["friend-group", "coworker", "close-friend", "school-senior"],
    formalityTags: ["casual", "balanced"],
    conversationScore: 6,
    hospitalityScore: 7,
    serviceScore: 7,
    accessScore: 9,
    noiseLevel: "lively",
    seatType: "room",
    spaceScore: 6,
    privateRoomAvailable: true,
    roomMinCapacity: 4,
    roomMinOrderAmount: 150000,
    roomTimeLimitMinutes: 120,
    reservationMethod: "phone",
    waitingRisk: 5,
    parkingAvailable: true,
    parkingType: "self",
    curatedReason:
      "여러 명이 함께하는 모임에 무난하고, 룸 좌석이 있어 대화도 편해요.",
    cautionNote: "금요일 저녁은 웨이팅이 있을 수 있어 미리 전화 예약을 추천해요.",
    lastVerifiedAt: "2026-06-22",
  }),
  place({
    id: "gomtang-jip",
    name: "정성곰탕 강남",
    category: "한식",
    cuisineTags: ["korean"],
    area: "gangnam",
    address: "서울 강남구 테헤란로1길 5 1층",
    lat: 37.499,
    lng: 127.029,
    priceMin: 15000,
    priceMax: 22000,
    capacityMin: 2,
    capacityMax: 6,
    relationshipTags: ["family", "close-friend", "school-senior"],
    formalityTags: ["casual", "balanced"],
    conversationScore: 7,
    hospitalityScore: 6,
    serviceScore: 7,
    accessScore: 8,
    noiseLevel: "moderate",
    seatType: "open",
    spaceScore: 5,
    privateRoomAvailable: false,
    reservationMethod: "available",
    waitingRisk: 4,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "부담 없는 가격으로 편하게 식사하며 이야기 나누기 좋은 곳이에요.",
    cautionNote: "점심시간엔 회전이 빨라 대화가 짧게 느껴질 수 있어요.",
    lastVerifiedAt: "2026-06-15",
  }),
  place({
    id: "wine-swimming",
    name: "쉼표 와인바",
    category: "와인바",
    cuisineTags: ["wine-alcohol"],
    area: "sinnonhyeon",
    address: "서울 서초구 반포대로28길 9 2층",
    lat: 37.5052,
    lng: 127.0258,
    priceMin: 40000,
    priceMax: 60000,
    capacityMin: 2,
    capacityMax: 6,
    relationshipTags: ["close-friend", "friend-group"],
    formalityTags: ["casual"],
    conversationScore: 7,
    hospitalityScore: 6,
    serviceScore: 7,
    accessScore: 7,
    noiseLevel: "lively",
    seatType: "wide",
    spaceScore: 6,
    privateRoomAvailable: false,
    reservationMethod: "phone",
    waitingRisk: 3,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason:
      "친한 친구들과 오래 앉아 술 한잔하며 이야기하기 좋은 와인바예요.",
    cautionNote: "저녁 9시 이후엔 소음이 커질 수 있어요.",
    lastVerifiedAt: "2026-06-05",
  }),
  place({
    id: "italian-tavola",
    name: "타볼라 논현",
    category: "이탈리안",
    cuisineTags: ["western"],
    area: "nonhyeon",
    address: "서울 강남구 논현로 534 1층",
    lat: 37.5095,
    lng: 127.024,
    priceMin: 30000,
    priceMax: 45000,
    capacityMin: 2,
    capacityMax: 8,
    relationshipTags: ["friend-group", "coworker", "close-friend", "school-senior"],
    formalityTags: ["casual", "balanced"],
    conversationScore: 6,
    hospitalityScore: 6,
    serviceScore: 6,
    accessScore: 7,
    noiseLevel: "lively",
    seatType: "open",
    spaceScore: 4,
    privateRoomAvailable: false,
    reservationMethod: "available",
    waitingRisk: 6,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason:
      "캐주얼하면서도 성의 있어 보이는 분위기라 친구·동료 모임에 무난해요.",
    cautionNote: "인기 시간대는 웨이팅이 20분 이상 걸릴 수 있어요.",
    lastVerifiedAt: "2026-06-12",
  }),
  place({
    id: "jokbal-myeongga",
    name: "명가족발 강남",
    category: "족발·보쌈",
    cuisineTags: ["meat"],
    area: "gangnam",
    address: "서울 강남구 강남대로102길 15 1층",
    lat: 37.4965,
    lng: 127.0283,
    priceMin: 25000,
    priceMax: 35000,
    capacityMin: 2,
    capacityMax: 10,
    relationshipTags: ["close-friend", "friend-group"],
    formalityTags: ["casual"],
    conversationScore: 5,
    hospitalityScore: 5,
    serviceScore: 6,
    accessScore: 9,
    noiseLevel: "lively",
    seatType: "wide",
    spaceScore: 5,
    privateRoomAvailable: false,
    reservationMethod: "available",
    waitingRisk: 5,
    parkingAvailable: true,
    parkingType: "self",
    curatedReason:
      "부담 없는 가격에 편하게 술 한잔 곁들이기 좋은 친구 모임용 장소예요.",
    cautionNote: "주말 저녁은 웨이팅이 길 수 있어요.",
    lastVerifiedAt: "2026-06-08",
  }),
  place({
    id: "omakase-eunmi",
    name: "온미",
    category: "스몰 오마카세",
    cuisineTags: ["japanese"],
    area: "sinnonhyeon",
    address: "서울 서초구 서초대로 397 5층",
    lat: 37.503,
    lng: 127.0265,
    priceMin: 100000,
    priceMax: 150000,
    capacityMin: 2,
    capacityMax: 4,
    relationshipTags: ["workplace-senior", "coworker"],
    formalityTags: ["hospitable", "formal"],
    conversationScore: 8,
    hospitalityScore: 10,
    serviceScore: 9,
    accessScore: 6,
    noiseLevel: "quiet",
    seatType: "semi-private",
    spaceScore: 7,
    privateRoomAvailable: false,
    reservationMethod: "difficult",
    waitingRisk: 1,
    parkingAvailable: true,
    parkingType: "valet",
    curatedReason:
      "소수 인원으로 확실하게 대접하고 싶을 때 어울리는 스몰 오마카세예요.",
    cautionNote: "예약 오픈과 동시에 마감되는 경우가 많아요.",
    lastVerifiedAt: "2026-05-28",
  }),
  place({
    id: "sundubu-jeongseong",
    name: "정성순두부 논현",
    category: "한식",
    cuisineTags: ["korean"],
    area: "nonhyeon",
    address: "서울 강남구 논현로 412 지하1층",
    lat: 37.5122,
    lng: 127.0205,
    priceMin: 12000,
    priceMax: 18000,
    capacityMin: 2,
    capacityMax: 6,
    relationshipTags: ["family", "close-friend"],
    formalityTags: ["casual", "balanced"],
    conversationScore: 6,
    hospitalityScore: 5,
    serviceScore: 6,
    accessScore: 7,
    noiseLevel: "moderate",
    seatType: "open",
    spaceScore: 4,
    privateRoomAvailable: false,
    reservationMethod: "available",
    waitingRisk: 4,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "가볍게 식사하며 청첩장을 전하기 좋은 부담 없는 곳이에요.",
    cautionNote: "점심 피크시간엔 대기가 있을 수 있어요.",
    lastVerifiedAt: "2026-06-20",
  }),
  place({
    id: "seafood-parang",
    name: "파랑해물 강남",
    category: "해산물",
    cuisineTags: ["seafood"],
    area: "gangnam",
    address: "서울 강남구 봉은사로 108 2층",
    lat: 37.5005,
    lng: 127.0295,
    priceMin: 45000,
    priceMax: 65000,
    capacityMin: 2,
    capacityMax: 8,
    relationshipTags: ["family", "coworker", "workplace-senior"],
    formalityTags: ["hospitable", "balanced"],
    conversationScore: 7,
    hospitalityScore: 8,
    serviceScore: 8,
    accessScore: 7,
    noiseLevel: "moderate",
    seatType: "room",
    spaceScore: 7,
    privateRoomAvailable: true,
    roomMinCapacity: 4,
    roomMinOrderAmount: 200000,
    roomTimeLimitMinutes: 120,
    reservationMethod: "phone",
    waitingRisk: 3,
    parkingAvailable: true,
    parkingType: "self",
    curatedReason:
      "가족이나 상사와 함께해도 부담스럽지 않은 정갈한 해산물 코스예요.",
    cautionNote: "인기 메뉴는 소진되면 대체 메뉴로 안내될 수 있어요.",
    lastVerifiedAt: "2026-06-14",
  }),
  place({
    id: "brunch-onnuri",
    name: "온누리 브런치 다이닝",
    category: "브런치·카페",
    cuisineTags: ["brunch-cafe"],
    area: "gangnam",
    address: "서울 강남구 강남대로62길 11 3층",
    lat: 37.4978,
    lng: 127.025,
    priceMin: 25000,
    priceMax: 35000,
    capacityMin: 2,
    capacityMax: 8,
    relationshipTags: ["friend-group", "close-friend"],
    formalityTags: ["casual"],
    conversationScore: 8,
    hospitalityScore: 6,
    serviceScore: 7,
    accessScore: 8,
    noiseLevel: "moderate",
    seatType: "wide",
    spaceScore: 5,
    privateRoomAvailable: false,
    reservationMethod: "available",
    waitingRisk: 5,
    parkingAvailable: false,
    parkingType: "none",
    curatedReason: "낮 시간 모임으로 가볍고 캐주얼하게 청첩장을 전하기 좋아요.",
    cautionNote: "주말 브런치 타임엔 대기 줄이 생길 수 있어요.",
    lastVerifiedAt: "2026-06-17",
  }),
  place({
    id: "gomjang-galbi",
    name: "곰장갈비 논현",
    category: "한우갈비",
    cuisineTags: ["meat", "korean"],
    area: "nonhyeon",
    address: "서울 강남구 논현로 583 1층",
    lat: 37.51,
    lng: 127.025,
    priceMin: 60000,
    priceMax: 90000,
    capacityMin: 2,
    capacityMax: 10,
    relationshipTags: ["workplace-senior", "family"],
    formalityTags: ["hospitable", "formal"],
    conversationScore: 7,
    hospitalityScore: 9,
    serviceScore: 8,
    accessScore: 6,
    noiseLevel: "moderate",
    seatType: "room",
    spaceScore: 8,
    privateRoomAvailable: true,
    roomMinCapacity: 4,
    roomMinOrderAmount: 300000,
    roomTimeLimitMinutes: 120,
    reservationMethod: "phone",
    waitingRisk: 2,
    parkingAvailable: true,
    parkingType: "valet",
    curatedReason:
      "가족 어른이나 상사를 모시고 든든하게 대접하기 좋은 한우 갈빗집이에요.",
    cautionNote: "주말 저녁은 룸 예약을 미리 확인하는 게 좋아요.",
    lastVerifiedAt: "2026-06-11",
  }),
];

export function getPlaceById(id: string): Place | undefined {
  return PLACES.find((p) => p.id === id);
}

/**
 * 홈 화면 랭킹 섹션용 임시 정렬 기준. 실제 조회수·저장수 집계가 아직 없어서,
 * 이미 갖고 있는 큐레이션 점수(대접감·대화가능성·서비스·접근성 평균)로 대체한다.
 * 트래픽 데이터가 쌓이면 이 함수만 실집계 기준으로 바꾸면 된다.
 */
export function getTopRatedPlaces(limit = 5): Place[] {
  // 대접감·서비스 점수는 가격이 높은 장소일수록 자연히 높게 나오는 경향이 있다.
  // 순수 품질 점수만으로 정렬하면 홈 화면 첫인상이 고가 오마카세 위주로 쏠려,
  // "청첩장 모임"이라는 다양한 예산대의 실제 사용 맥락과 멀어진다.
  // 1인 평균가에 완만한 페널티를 줘서 가격대가 고르게 섞여 보이도록 보정한다.
  const valueScore = (p: Place) => {
    const quality = (p.hospitalityScore + p.conversationScore + p.serviceScore + p.accessScore) / 4;
    const avgPrice = (p.priceMin + p.priceMax) / 2;
    return quality - avgPrice / 50000;
  };
  return [...PLACES].sort((a, b) => valueScore(b) - valueScore(a)).slice(0, limit);
}
