import type { Place } from "./types";

/**
 * MVP 데모/프로토타이핑용 예시 데이터입니다.
 * 실제 존재하는 매장을 검증한 정보가 아니라 PRD 10.1 스키마 구조를 보여주기 위한
 * 플레이스홀더이며, 런칭 전 자체 큐레이션 데이터로 교체되어야 합니다(PRD 9.1 참고).
 * 지도 링크는 특정 리스팅을 단정하지 않도록 이름+주소 기반 "검색" 링크로 생성합니다.
 */

function buildMapUrls(name: string, address: string) {
  const q = encodeURIComponent(`${name} ${address}`);
  return {
    mapUrlNaver: `https://map.naver.com/p/search/${q}`,
    mapUrlKakao: `https://map.kakao.com/?q=${q}`,
  };
}

function place(p: Omit<Place, "mapUrlNaver" | "mapUrlKakao">): Place {
  return { ...p, ...buildMapUrls(p.name, p.address) };
}

export const PLACES: Place[] = [
  place({
    id: "onki-hansang",
    name: "온기한상 강남",
    category: "한정식",
    area: "gangnam",
    address: "서울 강남구 강남대로94길 12 3층",
    priceMin: 45000,
    priceMax: 60000,
    capacityMin: 2,
    capacityMax: 8,
    relationshipTags: ["family", "senior", "coworker"],
    moodTags: ["hospitable", "quiet-talk", "stable-service"],
    avoidTags: ["too-expensive"],
    alcoholFit: 6,
    nonAlcoholFit: 9,
    conversationScore: 8,
    hospitalityScore: 9,
    accessScore: 8,
    reservationDifficulty: 6,
    waitingRisk: 2,
    serviceScore: 9,
    privateRoomAvailable: true,
    curatedReason:
      "가족이나 선배님을 모시는 자리에 어울리는 정갈한 한정식 코스로, 룸 좌석에서 조용히 대화하기 좋아요.",
    cautionNote: "저녁 시간대는 최소 3일 전 예약을 권장해요.",
    lastVerifiedAt: "2026-06-18",
  }),
  place({
    id: "sueot-sikdang",
    name: "수어당 논현",
    category: "한식",
    area: "nonhyeon",
    address: "서울 강남구 논현로 645 2층",
    priceMin: 50000,
    priceMax: 70000,
    capacityMin: 2,
    capacityMax: 6,
    relationshipTags: ["senior", "coworker", "family"],
    moodTags: ["quiet-talk", "hospitable", "stable-service"],
    avoidTags: ["hard-reservation", "too-expensive"],
    alcoholFit: 7,
    nonAlcoholFit: 8,
    conversationScore: 9,
    hospitalityScore: 9,
    accessScore: 6,
    reservationDifficulty: 8,
    waitingRisk: 2,
    serviceScore: 9,
    privateRoomAvailable: true,
    curatedReason:
      "선배나 상사를 모시는 자리에 맞춰진 룸 중심 한식당으로 대접하는 느낌이 확실해요.",
    cautionNote: "주말 저녁은 예약이 빨리 마감되니 1주일 전에는 확인해보세요.",
    lastVerifiedAt: "2026-06-10",
  }),
  place({
    id: "nonhyeon-sushi-on",
    name: "스시온 논현",
    category: "일식·오마카세",
    area: "nonhyeon",
    address: "서울 강남구 논현로145길 8 1층",
    priceMin: 90000,
    priceMax: 130000,
    capacityMin: 2,
    capacityMax: 4,
    relationshipTags: ["close-friend", "senior", "coworker"],
    moodTags: ["hospitable", "quiet-talk"],
    avoidTags: ["too-expensive", "hard-reservation"],
    alcoholFit: 8,
    nonAlcoholFit: 6,
    conversationScore: 7,
    hospitalityScore: 10,
    accessScore: 7,
    reservationDifficulty: 9,
    waitingRisk: 1,
    serviceScore: 9,
    privateRoomAvailable: false,
    curatedReason:
      "특별히 대접하고 싶은 소수 모임에 맞는 오마카세로, 격식 있는 분위기를 원할 때 좋아요.",
    cautionNote: "예약이 2주 전에 마감되는 경우가 많아 서둘러야 해요.",
    lastVerifiedAt: "2026-05-30",
  }),
  place({
    id: "le-pavillon",
    name: "르파비용 신논현",
    category: "프렌치 다이닝",
    area: "sinnonhyeon",
    address: "서울 서초구 서초대로77길 20 4층",
    priceMin: 80000,
    priceMax: 110000,
    capacityMin: 2,
    capacityMax: 6,
    relationshipTags: ["senior", "coworker"],
    moodTags: ["hospitable", "quiet-talk", "stable-service"],
    avoidTags: ["too-expensive", "hard-reservation", "too-formal"],
    alcoholFit: 8,
    nonAlcoholFit: 6,
    conversationScore: 8,
    hospitalityScore: 10,
    accessScore: 8,
    reservationDifficulty: 8,
    waitingRisk: 2,
    serviceScore: 10,
    privateRoomAvailable: true,
    curatedReason: "격식 있게 대접해야 하는 상사·선배 모임에 맞는 코스 다이닝이에요.",
    cautionNote: "코스 진행 시간이 길어 2시간 이상 여유를 두는 게 좋아요.",
    lastVerifiedAt: "2026-06-01",
  }),
  place({
    id: "hwaroyeon",
    name: "화로연 강남점",
    category: "숯불구이",
    area: "gangnam",
    address: "서울 강남구 강남대로 428 지하1층",
    priceMin: 35000,
    priceMax: 50000,
    capacityMin: 4,
    capacityMax: 10,
    relationshipTags: ["friend-group", "coworker", "close-friend"],
    moodTags: ["casual-sincere", "hospitable"],
    avoidTags: ["long-wait", "too-loud"],
    alcoholFit: 9,
    nonAlcoholFit: 5,
    conversationScore: 6,
    hospitalityScore: 7,
    accessScore: 9,
    reservationDifficulty: 4,
    waitingRisk: 6,
    serviceScore: 7,
    privateRoomAvailable: true,
    curatedReason:
      "여러 명이 함께하는 모임에 무난하고, 룸 좌석이 있어 대화도 편해요.",
    cautionNote: "금요일 저녁은 웨이팅이 있을 수 있어 미리 전화 예약을 추천해요.",
    lastVerifiedAt: "2026-06-22",
  }),
  place({
    id: "gomtang-jip",
    name: "정성곰탕 강남",
    category: "한식",
    area: "gangnam",
    address: "서울 강남구 테헤란로1길 5 1층",
    priceMin: 15000,
    priceMax: 22000,
    capacityMin: 2,
    capacityMax: 6,
    relationshipTags: ["family", "close-friend"],
    moodTags: ["not-too-much", "quiet-talk"],
    avoidTags: [],
    alcoholFit: 3,
    nonAlcoholFit: 9,
    conversationScore: 7,
    hospitalityScore: 6,
    accessScore: 8,
    reservationDifficulty: 1,
    waitingRisk: 3,
    serviceScore: 7,
    privateRoomAvailable: false,
    curatedReason: "부담 없는 가격으로 편하게 식사하며 이야기 나누기 좋은 곳이에요.",
    cautionNote: "점심시간엔 회전이 빨라 대화가 짧게 느껴질 수 있어요.",
    lastVerifiedAt: "2026-06-15",
  }),
  place({
    id: "wine-swimming",
    name: "쉼표 와인바",
    category: "와인바",
    area: "sinnonhyeon",
    address: "서울 서초구 반포대로28길 9 2층",
    priceMin: 40000,
    priceMax: 60000,
    capacityMin: 2,
    capacityMax: 6,
    relationshipTags: ["close-friend", "friend-group"],
    moodTags: ["casual-sincere", "long-stay"],
    avoidTags: ["too-loud", "bar-like"],
    alcoholFit: 9,
    nonAlcoholFit: 3,
    conversationScore: 7,
    hospitalityScore: 6,
    accessScore: 7,
    reservationDifficulty: 3,
    waitingRisk: 3,
    serviceScore: 7,
    privateRoomAvailable: false,
    curatedReason:
      "친한 친구들과 오래 앉아 술 한잔하며 이야기하기 좋은 와인바예요.",
    cautionNote: "저녁 9시 이후엔 소음이 커질 수 있어요.",
    lastVerifiedAt: "2026-06-05",
  }),
  place({
    id: "italian-tavola",
    name: "타볼라 논현",
    category: "이탈리안",
    area: "nonhyeon",
    address: "서울 강남구 논현로 534 1층",
    priceMin: 30000,
    priceMax: 45000,
    capacityMin: 2,
    capacityMax: 8,
    relationshipTags: ["friend-group", "coworker", "close-friend"],
    moodTags: ["casual-sincere", "not-too-much"],
    avoidTags: ["long-wait"],
    alcoholFit: 6,
    nonAlcoholFit: 7,
    conversationScore: 6,
    hospitalityScore: 6,
    accessScore: 7,
    reservationDifficulty: 3,
    waitingRisk: 7,
    serviceScore: 6,
    privateRoomAvailable: false,
    curatedReason:
      "캐주얼하면서도 성의 있어 보이는 분위기라 친구·동료 모임에 무난해요.",
    cautionNote: "인기 시간대는 웨이팅이 20분 이상 걸릴 수 있어요.",
    lastVerifiedAt: "2026-06-12",
  }),
  place({
    id: "jokbal-myeongga",
    name: "명가족발 강남",
    category: "족발·보쌈",
    area: "gangnam",
    address: "서울 강남구 강남대로102길 15 1층",
    priceMin: 25000,
    priceMax: 35000,
    capacityMin: 2,
    capacityMax: 10,
    relationshipTags: ["close-friend", "friend-group"],
    moodTags: ["not-too-much", "casual-sincere"],
    avoidTags: ["long-wait", "too-loud"],
    alcoholFit: 8,
    nonAlcoholFit: 5,
    conversationScore: 5,
    hospitalityScore: 5,
    accessScore: 9,
    reservationDifficulty: 2,
    waitingRisk: 7,
    serviceScore: 6,
    privateRoomAvailable: false,
    curatedReason:
      "부담 없는 가격에 편하게 술 한잔 곁들이기 좋은 친구 모임용 장소예요.",
    cautionNote: "주말 저녁은 웨이팅이 길 수 있어요.",
    lastVerifiedAt: "2026-06-08",
  }),
  place({
    id: "omakase-eunmi",
    name: "온미",
    category: "스몰 오마카세",
    area: "sinnonhyeon",
    address: "서울 서초구 서초대로 397 5층",
    priceMin: 100000,
    priceMax: 150000,
    capacityMin: 2,
    capacityMax: 4,
    relationshipTags: ["senior", "coworker"],
    moodTags: ["hospitable", "quiet-talk"],
    avoidTags: ["too-expensive", "hard-reservation"],
    alcoholFit: 7,
    nonAlcoholFit: 6,
    conversationScore: 8,
    hospitalityScore: 10,
    accessScore: 6,
    reservationDifficulty: 9,
    waitingRisk: 1,
    serviceScore: 9,
    privateRoomAvailable: false,
    curatedReason:
      "소수 인원으로 확실하게 대접하고 싶을 때 어울리는 스몰 오마카세예요.",
    cautionNote: "예약 오픈과 동시에 마감되는 경우가 많아요.",
    lastVerifiedAt: "2026-05-28",
  }),
  place({
    id: "sundubu-jeongseong",
    name: "정성순두부 논현",
    category: "한식",
    area: "nonhyeon",
    address: "서울 강남구 논현로 412 지하1층",
    priceMin: 12000,
    priceMax: 18000,
    capacityMin: 2,
    capacityMax: 6,
    relationshipTags: ["family", "close-friend"],
    moodTags: ["not-too-much", "quiet-talk"],
    avoidTags: [],
    alcoholFit: 2,
    nonAlcoholFit: 9,
    conversationScore: 6,
    hospitalityScore: 5,
    accessScore: 7,
    reservationDifficulty: 1,
    waitingRisk: 4,
    serviceScore: 6,
    privateRoomAvailable: false,
    curatedReason: "가볍게 식사하며 청첩장을 전하기 좋은 부담 없는 곳이에요.",
    cautionNote: "점심 피크시간엔 대기가 있을 수 있어요.",
    lastVerifiedAt: "2026-06-20",
  }),
  place({
    id: "seafood-parang",
    name: "파랑해물 강남",
    category: "해산물",
    area: "gangnam",
    address: "서울 강남구 봉은사로 108 2층",
    priceMin: 45000,
    priceMax: 65000,
    capacityMin: 2,
    capacityMax: 8,
    relationshipTags: ["family", "coworker", "senior"],
    moodTags: ["hospitable", "stable-service"],
    avoidTags: ["too-expensive"],
    alcoholFit: 7,
    nonAlcoholFit: 7,
    conversationScore: 7,
    hospitalityScore: 8,
    accessScore: 7,
    reservationDifficulty: 5,
    waitingRisk: 4,
    serviceScore: 8,
    privateRoomAvailable: true,
    curatedReason:
      "가족이나 상사와 함께해도 부담스럽지 않은 정갈한 해산물 코스예요.",
    cautionNote: "인기 메뉴는 소진되면 대체 메뉴로 안내될 수 있어요.",
    lastVerifiedAt: "2026-06-14",
  }),
  place({
    id: "brunch-onnuri",
    name: "온누리 브런치 다이닝",
    category: "브런치·카페",
    area: "gangnam",
    address: "서울 강남구 강남대로62길 11 3층",
    priceMin: 25000,
    priceMax: 35000,
    capacityMin: 2,
    capacityMax: 8,
    relationshipTags: ["friend-group", "close-friend"],
    moodTags: ["not-too-much", "casual-sincere"],
    avoidTags: [],
    alcoholFit: 4,
    nonAlcoholFit: 9,
    conversationScore: 8,
    hospitalityScore: 6,
    accessScore: 8,
    reservationDifficulty: 3,
    waitingRisk: 5,
    serviceScore: 7,
    privateRoomAvailable: false,
    curatedReason: "낮 시간 모임으로 가볍고 캐주얼하게 청첩장을 전하기 좋아요.",
    cautionNote: "주말 브런치 타임엔 대기 줄이 생길 수 있어요.",
    lastVerifiedAt: "2026-06-17",
  }),
  place({
    id: "gomjang-galbi",
    name: "곰장갈비 논현",
    category: "한우갈비",
    area: "nonhyeon",
    address: "서울 강남구 논현로 583 1층",
    priceMin: 60000,
    priceMax: 90000,
    capacityMin: 2,
    capacityMax: 10,
    relationshipTags: ["senior", "family"],
    moodTags: ["hospitable", "quiet-talk", "stable-service"],
    avoidTags: ["too-expensive"],
    alcoholFit: 7,
    nonAlcoholFit: 6,
    conversationScore: 7,
    hospitalityScore: 9,
    accessScore: 6,
    reservationDifficulty: 6,
    waitingRisk: 3,
    serviceScore: 8,
    privateRoomAvailable: true,
    curatedReason:
      "가족 어른이나 상사를 모시고 든든하게 대접하기 좋은 한우 갈빗집이에요.",
    cautionNote: "주말 저녁은 룸 예약을 미리 확인하는 게 좋아요.",
    lastVerifiedAt: "2026-06-11",
  }),
];

export function getPlaceById(id: string): Place | undefined {
  return PLACES.find((p) => p.id === id);
}
